### ISSUE TITLE
Tailwind responsive classes not working

### ISSUE THREAD

**Issue by bernhardh** [nibri10/nova-grid#7]
Not sure if this is the right place for my question...

When applying classes like in your example, everything works:

```
 Text::make('name') ->size('w-1/3')
....
```

![image](https://user-images.githubusercontent.com/642292/70832274-ff429200-1df4-11ea-9b31-b9192404f56d.png)

but it is of course not really userfriendly on small screens due to small fields. 

![image](https://user-images.githubusercontent.com/642292/70832323-1bdeca00-1df5-11ea-83bc-0d6042f01922.png)

But when using tailwind responsive prefixes, like `md:w-1/3`,the result is a complete mess

![image](https://user-images.githubusercontent.com/642292/70832242-e803a480-1df4-11ea-8a5c-58b5bb917599.png)

Any ideas? Btw. I am using the Nova Responsive Theme Package.

**Comment by bernhardh** [comment]
Ok, just if someone has the same problem, you will have to add somewhere these responsive classses, since the aren't included in the nova specific tailwind version.

For example, if you would like to use `1/4`, `1/3` and `1/2` width columns for screens > 768:

```css
@media (min-width: 768px) {
    .md\:w-1\/4 {
        width: 25%;
    }
    .md\:w-1\/3 {
        width: 33.3333333%;
    }
    .md\:w-1\/2 {
        width: 50%;
    }
}
```
